jenkins-zh/jenkins-zh

- .gitignore
- content/about/social-media.md
第三行应该是description
之前review #25  时疏忽了
> typo fix for social-media.md

- content/about/social-media.md
> Fix the markdown table issues

- .github/settings.yml
We donot have so many reviewers now
> Set approve review account as 1

- scripts/change-format.sh
> Fix the logic of format

- content/about/star-plan.md
> add the tickets presentation record of JUCC

- content/tutorial/management/mirror/_index.md
- content/tutorial/management/plugin/update-center.md
> 在教程 镜像源中增加华为镜像仓

- content/partner/ucloud.md
- content/sponsor/ucloud.md
> Change the link of UCloud

- .github/workflows/dispatch-deploy.yaml
> 修改workflows问题

- content/about/star-plan.md
> [维护] 添加第三期奖励名单

- content/meeting/2020-04-15.md
> Add meeting notes for 2020-04-15

- config.toml
> [维护] 修改文件或文件夹名称大写读不出的问题

- content/wechat/articles/2020/04/2020-04-22-scale-your-jenkins-agents-using-kubernetes.md
> [维护] 修改格式问题

- Makefile
- content/wechat/articles/2020/05/2020-05-06-using-a-k3s-kubernetes-cluster-for-your-gitlab-project.md
> [维护] 修改图片名和注释掉make命令中多余步骤

- content/meeting/2020-05-13.md
> Add meeting note of 2020-05-13

- .github/PULL_REQUEST_TEMPLATE.md
> Update the terms of articles

- content/wechat/articles/2020/04/2020-04-30-jenkins-kubesphere-partner.md
This is the first edition of this doc
> [投稿-2020-05-19] add jenkins-kubesphere-partner.md

- content/wechat/articles/2020/05/2020-05-19-jenkins-kubesphere-partner.md
> [维护] 修改日期和作者

- content/wechat/articles/2020/06/2020-06-03-monitoring-linux-processes-using-prometheus-and-grafana.md
> [维护] 修改文章内容-图片路径

- content/meeting/2020-06-10.md
> Add meeting of 2020-06-10

- content/about/star-plan.md
> Add some reward records

- content/about/social-media.md
> [维护] 开源中国的文章现在可以自动同步了

- content/about/sponsors-list.md
> [维护] open4u域名购买

- content/wechat/articles/2020/08/2020-08-05-ci-cd-with-argo-on-kubernetes.md
> [维护] 去除无用空格

- content/about/star-plan.md
> 提交第四期社区贡献奖励名单 20200831

- content/meeting/2020-09-02.md
> [维护] Add meeting notes for 2020-09-02

- content/wechat/articles/2020/09/2020-09-25-github-checks-api-plugin-project-coding-phase-3.md
> [维护] 修改图片文件名

- content/wechat/articles/2020/09/2020-09-27-hacktoberfest.md
> [维护] Fix the wrong image path of hacktoberfest-2020.svg

- content/tutorial/management/plugin/update-center.md
> [维护] 添加镜像源地址

- content/tutorial/management/cli/_index.md
> [维护] 修改错误路径

- themes/hugo-jenkins-theme/layouts/partials/site-footer.html
原url做了二次跳转，先经过了http，导致https检测有些问题
> [维护] 更新url地址

- .github/workflows/deploy-to-github-page.yaml
> [维护] Using bot committer

- README-zh.md
- README.md
> [维护] Add a badge for hints count for this repository

- .github/workflows/backup.yaml
> Backup git repo to Code China

- content/tutorial/get-started/install/war.md
> Add a tutorial of Jenkins war installation

- content/wechat/articles/2020/10/2020-10-12-contributors-recruit.md
> [原创-2020-10-12] Jenkins 系列视频教程制作组招募

- content/about/social-media.md
> [运维] Change the url of Jenkins in CSDN blog

- content/tutorial/_index.md
> [维护] Add link of bilibili

- content/tutorial/management/plugin/update-center.md
Jenkins mirror update center generator.
> add jenkins china update center mirror

- themes/hugo-jenkins-theme/layouts/partials/site-footer.html
We don't have enough time to maintain of all them
> [维护]Remove youku and weibo

- themes/hugo-jenkins-theme/layouts/partials/site-footer.html
> [维护] Add a slack address

- content/tutorial/get-started/install/label.md
> Add a tutorial of Jenkins node label intro

- content/tutorial/management/agent/docker-jnlp.md
hold on to this pr until https://github.com/jenkins-zh/jenkins-cli/pull/488 get merged
> [维护]Add another more simple command to start Jenkins agent

- content/about/star-plan.md
> [维护] 第五期激励名单

- OWNERS
> [维护] Add file OWNERS

- content/meeting/2021-03-03.md
> Add meeting notes for 2021 03 03

- themes/hugo-jenkins-theme/layouts/partials/site-footer.html
> Change the youtube channel from personal link to the brand link

- content/sponsor/hogwarts.md
- content/sponsor/juzi.md
- content/sponsor/ucloud.md
- themes/hugo-jenkins-theme/layouts/partials/home-page-sections/sponsors.html
> Update the sponsor list

- content/partner/kubesphere.md
- content/partner/testerhome.md
> Update the partner list

- content/wechat/articles/OWNERS
@0N0thing 长期以来为社区提供多很多的翻译稿，这个 PR 把他设置为 reviewer，欢迎帮助社区一起 review 文章。
> Add 0N0thing as a reviewer under content/wechat/articles

- content/about/summer-2021.md
> 添加暑期计划2021项目提议～通过 CLI 对 Jenkins 实现安全升级

- content/wechat/articles/2021/07/2021-07-03-jenkins-JCasC-tutorial-translation.md
> [维护] 修改图片路径，使用本仓库的，而不是外链

- content/wechat/articles/2021/07/2021-07-03-jenkins-JCasC-tutorial-translation.md
> [维护] 修改翻译者填写错误导致无法编译问题

- content/sponsor/sonic.md
> 增加赞助者 Sonic 云真机

- content/tutorial/management/backup-restore/backup.md
- content/tutorial/management/backup-restore/demo.md
> Update and rename demo.md to backup.md
